Gimbal control
sensyn-robotics/sensyn_dji_gimbal_action-ros pull request #1
Opened 2023-05-12 02:07 UTC by YusukeTakase-Sensyn

control gimbal, camera, camera param by action

2023-07-11 07:44 UTC, MasahiroOgawa requested changes

2023-07-11 07:44 UTC, MasahiroOgawa commented on include/action_type_definition.h
> +std::map<int, std::string> map_GimbalCameraAction = {
Why do you need to define this? You already defined enum class, so you can use it by the name.

2023-07-11 07:44 UTC, MasahiroOgawa commented on CMakeLists.txt
> +find_package(PCL REQUIRED)
Why do you need PCL for gimbal control?
If this include some recognition module, it should be separeted.

2023-07-11 07:44 UTC, MasahiroOgawa commented on include/dji_gimbal_camera_action_client.h
> +namespace sr {
Do we always use namespace sr?
I think it is clearer to use sensyn.

2023-07-11 07:44 UTC, MasahiroOgawa commented on include/dji_gimbal_camera_action_client.h
> +        bool requestTaskAimCamera(const double roll, const double pitch, const double yaw, const double zoom) ;
I you use roll pitch yaw as an angle representation, you need to specify the order explicitly.
If you use the same order of DJI definition, you should write the link to the doc in the code.

2023-07-11 07:44 UTC, MasahiroOgawa commented on src/dji_camera_action_server.cpp
> +      ros::Duration(2.0).sleep();
You should create the variable for this 2.0 [sec].

2023-07-11 07:44 UTC, MasahiroOgawa commented on src/dji_gimbal_camera_action_server.cpp
> +
What happen if the delay is few second?
Can you suppress the vibration?
If no, it's better where we should update the gimbal control.

2024-04-19 06:55 UTC, ohtt commented on CMakeLists.txt
> +find_package(PCL REQUIRED)
pclは消したほうがいいかな

2024-04-26 07:36 UTC, closed without merging